language: go
sudo: required

go:
  - 1.6
  - 1.7
  - 1.8

go_import_path: github.com/gemnasium/migrate

services:
  - docker

before_install:
    - sed -i -e 's/golang/golang:'"$TRAVIS_GO_VERSION"'/' docker-compose.yml

script: make test
